CREATE TABLE IF NOT EXISTS MBL_DEVICE
(
     MOBILE_DEVICE_ID      VARCHAR(45) NOT NULL,
     REG_ID                VARCHAR(45) NOT NULL,
     IMEI                  VARCHAR(45) NOT NULL,
     IMSI                  VARCHAR(45) NOT NULL,
     OS_VERSION            VARCHAR(45) NOT NULL,
     DEVICE_MODEL          VARCHAR(45) NOT NULL,
     VENDOR                VARCHAR(45) NOT NULL,
     PRIMARY KEY (MOBILE_DEVICE_ID)
);