CREATE TABLE IF NOT EXISTS MBL_OS_VERSION
(
     VERSION_ID         INT NOT NULL AUTO_INCREMENT,
     NAME               VARCHAR(45) NULL DEFAULT NULL,
     PRIMARY KEY (VERSION_ID)
);

CREATE TABLE IF NOT EXISTS MBL_DEVICE_MODEL
(
     MODEL_ID         INT NOT NULL AUTO_INCREMENT,
     MODEL            VARCHAR(45) NULL DEFAULT NULL,
     PRIMARY KEY (MODEL_ID)
);

 CREATE TABLE IF NOT EXISTS MBL_VENDOR
(
     VENDOR_ID         INT NOT NULL AUTO_INCREMENT,
     VENDOR            VARCHAR(45) NULL DEFAULT NULL,
     PRIMARY KEY (VENDOR_ID)
);

CREATE TABLE IF NOT EXISTS MBL_DEVICE
(
     MOBILE_DEVICE_ID      VARCHAR(45) NOT NULL,
     REG_ID                VARCHAR(45) NOT NULL,
     IMEI                  VARCHAR(45) NOT NULL,
     IMSI                  VARCHAR(45) NOT NULL,
     OS_VERSION_ID         INT NOT NULL,
     DEVICE_MODEL_ID       INT NOT NULL,
     VENDOR_ID             INT NOT NULL,
     PRIMARY KEY (MOBILE_DEVICE_ID),
     CONSTRAINT fk_DEVICE_OS_VERSION1 FOREIGN KEY (OS_VERSION_ID )
     REFERENCES MBL_OS_VERSION (VERSION_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION,
     CONSTRAINT fk_DEVICE_DEVICE_MODEL2 FOREIGN KEY (DEVICE_MODEL_ID )
     REFERENCES MBL_DEVICE_MODEL (MODEL_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION,
     CONSTRAINT fk_DEVICE_VENDOR1 FOREIGN KEY (VENDOR_ID )
     REFERENCES MBL_VENDOR (VENDOR_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION
);